# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lukas/ClionProjects/tony

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lukas/ClionProjects/tony

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukas/ClionProjects/tony/CMakeFiles /home/lukas/ClionProjects/tony/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukas/ClionProjects/tony/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tony

# Build rule for target.
tony: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tony
.PHONY : tony

# fast build rule for target.
tony/fast:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/build
.PHONY : tony/fast

MelodyReader.o: MelodyReader.cpp.o

.PHONY : MelodyReader.o

# target to build an object file
MelodyReader.cpp.o:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/MelodyReader.cpp.o
.PHONY : MelodyReader.cpp.o

MelodyReader.i: MelodyReader.cpp.i

.PHONY : MelodyReader.i

# target to preprocess a source file
MelodyReader.cpp.i:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/MelodyReader.cpp.i
.PHONY : MelodyReader.cpp.i

MelodyReader.s: MelodyReader.cpp.s

.PHONY : MelodyReader.s

# target to generate assembly for a file
MelodyReader.cpp.s:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/MelodyReader.cpp.s
.PHONY : MelodyReader.cpp.s

Tone.o: Tone.cpp.o

.PHONY : Tone.o

# target to build an object file
Tone.cpp.o:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/Tone.cpp.o
.PHONY : Tone.cpp.o

Tone.i: Tone.cpp.i

.PHONY : Tone.i

# target to preprocess a source file
Tone.cpp.i:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/Tone.cpp.i
.PHONY : Tone.cpp.i

Tone.s: Tone.cpp.s

.PHONY : Tone.s

# target to generate assembly for a file
Tone.cpp.s:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/Tone.cpp.s
.PHONY : Tone.cpp.s

ToneGenerator.o: ToneGenerator.cpp.o

.PHONY : ToneGenerator.o

# target to build an object file
ToneGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/ToneGenerator.cpp.o
.PHONY : ToneGenerator.cpp.o

ToneGenerator.i: ToneGenerator.cpp.i

.PHONY : ToneGenerator.i

# target to preprocess a source file
ToneGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/ToneGenerator.cpp.i
.PHONY : ToneGenerator.cpp.i

ToneGenerator.s: ToneGenerator.cpp.s

.PHONY : ToneGenerator.s

# target to generate assembly for a file
ToneGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/ToneGenerator.cpp.s
.PHONY : ToneGenerator.cpp.s

WavFile.o: WavFile.cpp.o

.PHONY : WavFile.o

# target to build an object file
WavFile.cpp.o:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/WavFile.cpp.o
.PHONY : WavFile.cpp.o

WavFile.i: WavFile.cpp.i

.PHONY : WavFile.i

# target to preprocess a source file
WavFile.cpp.i:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/WavFile.cpp.i
.PHONY : WavFile.cpp.i

WavFile.s: WavFile.cpp.s

.PHONY : WavFile.s

# target to generate assembly for a file
WavFile.cpp.s:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/WavFile.cpp.s
.PHONY : WavFile.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/tony.dir/build.make CMakeFiles/tony.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tony"
	@echo "... MelodyReader.o"
	@echo "... MelodyReader.i"
	@echo "... MelodyReader.s"
	@echo "... Tone.o"
	@echo "... Tone.i"
	@echo "... Tone.s"
	@echo "... ToneGenerator.o"
	@echo "... ToneGenerator.i"
	@echo "... ToneGenerator.s"
	@echo "... WavFile.o"
	@echo "... WavFile.i"
	@echo "... WavFile.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

